name: run_tsps_e2e_service_test_real_sample.yml

on:
  pull_request: # TODO: remove this before merge
  workflow_dispatch: # change this to workflow_call before merge
    inputs:
      env-name:
        description: 'Live environment to run the test against (dev or staging)'
        required: true
        type: string
        default: 'staging'
      repo_branch:
        description: 'Branch to run tests on'
        required: true
        default: 'main'
        type: string
      input_vcf_file_name:
        description: 'Name of the input VCF file to use in the test (note: just the file name and not the entire path)'
        required: true
        default: 'NA12878_10_samples_chr1_chr20.vcf.gz' # small VCF file with 10 samples, chr1 and chr20 data only
        type: string

jobs:
  run-e2e-test-job:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write
    steps:
      - name: "Checkout dsp-reusable-workflows"
        uses: actions/checkout@v3
        with:
          ref: ${{ inputs.repo_branch }}
          repository: broadinstitute/dsp-reusable-workflows
          path: dsp-reusable-workflows/
      - name: Set up python
        id: setup-python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'
      - name: Install dependencies
        run: |
          cd dsp-reusable-workflows/e2e-test/resources/teaspoons/
          pip install -r requirements.txt
      - name: Generate OAuth2 2.0 access token for Terra user
        id: 'obtain_user_token'
        uses: google-github-actions/auth@v1
        with:
          token_format: 'access_token'
          workload_identity_provider: 'projects/1038484894585/locations/global/workloadIdentityPools/github-wi-pool/providers/github-wi-provider'
          service_account: 'firecloud-qa@broad-dsde-qa.iam.gserviceaccount.com'
          access_token_scopes: 'profile, email, openid'
          access_token_subject: 'hermione.owner@quality.firecloud.org'
          export_environment_variables: false
      - name: Generate OAuth2 2.0 access token for admin user and billing project owner
        id: 'obtain_admin_token'
        uses: google-github-actions/auth@v1
        with:
          token_format: 'access_token'
          workload_identity_provider: 'projects/1038484894585/locations/global/workloadIdentityPools/github-wi-pool/providers/github-wi-provider'
          service_account: 'firecloud-qa@broad-dsde-qa.iam.gserviceaccount.com'
          access_token_scopes: 'openid, https://www.googleapis.com/auth/userinfo.email, https://www.googleapis.com/auth/userinfo.profile, https://www.googleapis.com/auth/cloud-billing'
          access_token_subject: 'dumbledore.admin@quality.firecloud.org'
          export_environment_variables: false
      - name: Run e2e test
        env:
          ENV_NAME: 'dev' # ${{ inputs.env-name }}
          USER_TOKEN: ${{ steps.obtain_user_token.outputs.access_token }}
          USER_EMAIL: 'hermione.owner@quality.firecloud.org'
          ADMIN_TOKEN: ${{ steps.obtain_admin_token.outputs.access_token }}
          INPUT_VCF_FILE_NAME: 'NA12878_10_samples_chr1_chr20.vcf.gz' # ${{ inputs.input_vcf_file_name }}
        run: |
          cd dsp-reusable-workflows/
          python e2e-test/teaspoons_gcp_e2e_service_test_real_sample.py
